### ISSUE TITLE
Flask error: RQLRuntimeError

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#109]
From `~/logs/flask/flask.log.2016-04-01`. Looks like we are getting several of these a day.

```
2016-04-01 05:42:02,917 - ERROR in app:1306 Exception on /api/plugins [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cache/__init__.py", line 245, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/vim/vim-awesome/web/api/api.py", line 136, in get_plugins
    results = get_search_index_cached()
  File "/usr/local/lib/python2.7/dist-packages/flask_cache/__init__.py", line 245, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/vim/vim-awesome/web/api/api.py", line 246, in get_search_index_cached
    return db.plugins.get_search_index()
  File "/home/vim/vim-awesome/db/plugins.py", line 565, in get_search_index
    plugins = map(to_json, query.run(r_conn()))
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/ast.py", line 96, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 228, in _start
    return self._send_query(query, global_optargs)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 329, in _send_query
    self._check_error_response(response, query.term)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 302, in _check_error_response
    raise RqlRuntimeError(message, term, frames)
RqlRuntimeError: Cannot perform read: Primary replica for shard ["", +inf) not available in:
r.table('plugins').without(['vimorg_long_desc', 'vimorg_install_details', 'github_long_desc', 'github_readme']).filter(lambda var_1: r.and_((r.row['slug'] != r.expr('vundle')), (r.row['slug'] != r.expr('neobundle-vim')), (r.row['slug'] != r.expr('neobundle-vim-back-to-december')), (r.row['slug'] != r.expr('pathogen-vim'))))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jonafato** [comment]
On a somewhat related note, how are developers notified of exceptions like this at the moment? Sentry has a free tier for [open source](https://getsentry.com/for/open-source/) projects. The integration is a simple Flask plugin, and I'd be happy to submit a pull request for that change.

(Sorry, this comment is borderline off-topic and not really relevant to the issue or its cause, but it might help to provide visibility into this issue and others like it.)

**Comment by captbaritone** [comment]
Possibly related: https://github.com/vim-awesome/vim-awesome/blob/master/crontab#L38-L46

**Comment by captbaritone** [comment]
We've seen several of these in Sentry for different endpoints. The one thing in common is:

    RqlRuntimeError: Cannot perform read: Primary replica for shard ["", +inf) not available in:

**Comment by thejsj** [comment]
Just dropping by and reading some of these issues: Noticing the error and your crontab, it seems that RethinkDB running out of memory seems probable (I'm guessing this is only running one db node, right?). As the comment said, decreasing RethinkDB cache size might be a possible solution.

**Comment by captbaritone** [comment]
@thejsj 

I was able to extract this from our logs:

```
2014-07-11T01:32:10.281602560 0.005021s info: Creating directory /home/vim/rethinkdb_data
2014-07-11T01:32:10.281834651 0.005253s info: Creating a default database for your convenience. (This is because you ran 'rethinkdb' without 'create', 'serve', or '--join', and the directory '/home/vim/rethinkdb_data' did not already exist.)
2014-07-11T01:32:10.281931778 0.005350s info: Running rethinkdb 1.13.0-0ubuntu1~trusty (GCC 4.8.2)...
2014-07-11T01:32:10.286647681 0.010066s info: Running on Linux 3.14.5-x86_64-linode42 x86_64
2014-07-11T01:32:10.286720673 0.010139s info: Using cache size of 2318 MB
2014-07-11T01:32:10.286933374 0.010352s info: Loading data from directory /home/vim/rethinkdb_data
2014-07-11T01:32:10.310014367 0.033433s error: Could not bind to cluster port: The address at localhost:29015 is reserved or already in use.
2016-04-15T05:34:43.475506752 0.006002s notice: Running rethinkdb 2.0.0+1~0trusty (GCC 4.8.2)...
2016-04-15T05:34:43.482396367 0.012895s notice: Running on Linux 4.4.0-x86_64-linode63 x86_64
2016-04-15T05:34:43.482504194 0.012999s notice: Loading data from directory /home/vim/rethinkdb_data
2016-04-15T05:34:43.491597578 0.022092s notice: Migrating existing cluster metadata to the new RethinkDB 1.16 format...
2016-04-15T05:34:43.497390159 0.027885s notice: Migrating existing auth metadata to the new RethinkDB 1.16 format...
2016-04-15T05:34:43.509119896 0.039615s info: Automatically using cache size of 100 MB
2016-04-15T05:34:43.510085757 0.040581s warn: Cache size does not leave much memory for server and query overhead (available memory: 940 MB).
2016-04-15T05:34:43.510097703 0.040592s warn: Cache size is very low and may impact performance.
2016-04-15T05:34:43.510958061 0.041453s error: TCP socket creation failed for port 29015: Address already in use.
```

I'm guessing that we are getting the default lower bound cache size because we are on a cheap VPS with very little memory.

I'm guessing reducing it further is not the right solution?

**Comment by thejsj** [comment]
Do you know how much memory exactly we have on it? Is RethinkDB the only thing running here? Going to ask in the RethinkDB slack channel about this.

**Comment by captbaritone** [comment]
@thejsj I believe we have 2GB of RAM. As far as I know the server is just running RethinkDB and the web-server.

**Comment by dalanmiller** [comment]
Any reason @captbaritone you guys are on `v1.13`?

**Comment by thejsj** [comment]
@dalanmiller Not sure if this ever got deployed, but there's a merged PR for upgrading: https://github.com/vim-awesome/vim-awesome/pull/141

**Comment by captbaritone** [comment]
Yes. The `2.0.0` deploy was run. We're running that on the server now.
