### ISSUE TITLE
gunicorn crashed

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#250]
Site was down for some time (502 Bad Gateway) because gunicorn crashed:

```
2016-08-17 05:42:04 [29438] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 174, in run
    self.sleep()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in sleep
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in <genexpr>
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
ValueError: I/O operation on closed file
```

Possibly related? https://github.com/benoitc/gunicorn/issues/863

**Comment by captbaritone** [comment]
Site went down again. @divad12 re-deployed to bring it back up (see Gitter chat for details). I've just upgraded us from Gunicorn v19.0.0 v19.6.0 which should include the above fix. 

I'm going to close this issue for now on the assumption that the upgrade should fix the issue.

I've also set up [uptimerobot.com](uptimerobot.com) so hopefully I'll notice down-time like this sooner in the future.

You can see from the below log, that this down-time was the same as the previous one, the time when it went down, the time when David brought it back up, and the time when I brought it up on Gunicorn 19.6.0

```
2016-09-04 05:42:02 [11976] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 174, in run
    self.sleep()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in sleep
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in <genexpr>
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
ValueError: I/O operation on closed file

2016-09-04 05:42:02 [536] [INFO] Worker exiting (pid: 536)
2016-09-04 05:42:02 [537] [INFO] Worker exiting (pid: 537)
2016-09-04 05:42:02 [538] [INFO] Worker exiting (pid: 538)
2016-09-04 05:42:02 [535] [INFO] Worker exiting (pid: 535)
2016-09-04 05:42:02 [539] [INFO] Worker exiting (pid: 539)
2016-09-05 02:43:00 [5879] [INFO] Starting gunicorn 19.0.0
2016-09-05 02:43:00 [5879] [INFO] Listening at: http://127.0.0.1:8000 (5879)
2016-09-05 02:43:00 [5879] [INFO] Using worker: sync
2016-09-05 02:43:00 [5885] [INFO] Booting worker with pid: 5885
2016-09-05 02:43:00 [5886] [INFO] Booting worker with pid: 5886
2016-09-05 02:43:00 [5887] [INFO] Booting worker with pid: 5887
2016-09-05 02:43:00 [5888] [INFO] Booting worker with pid: 5888
2016-09-05 02:43:00 [5889] [INFO] Booting worker with pid: 5889
2016-09-05 03:36:46 [5879] [INFO] Handling signal: term
2016-09-05 03:36:46 [5886] [INFO] Worker exiting (pid: 5886)
2016-09-05 03:36:46 [5888] [INFO] Worker exiting (pid: 5888)
2016-09-05 03:36:46 [5889] [INFO] Worker exiting (pid: 5889)
2016-09-05 03:36:46 [5885] [INFO] Worker exiting (pid: 5885)
2016-09-05 03:36:46 [5887] [INFO] Worker exiting (pid: 5887)
2016-09-05 03:36:46 [5879] [INFO] Shutting down: Master
[2016-09-05 03:36:47 +0000] [6284] [INFO] Starting gunicorn 19.6.0
[2016-09-05 03:36:47 +0000] [6284] [INFO] Listening at: http://127.0.0.1:8000 (6284)
[2016-09-05 03:36:47 +0000] [6284] [INFO] Using worker: sync
[2016-09-05 03:36:47 +0000] [6290] [INFO] Booting worker with pid: 6290
[2016-09-05 03:36:47 +0000] [6291] [INFO] Booting worker with pid: 6291
[2016-09-05 03:36:47 +0000] [6292] [INFO] Booting worker with pid: 6292
[2016-09-05 03:36:47 +0000] [6293] [INFO] Booting worker with pid: 6293
[2016-09-05 03:36:47 +0000] [6294] [INFO] Booting worker with pid: 6294
```
