### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by deltaxflux** [vim-awesome/vim-awesome#357]
**After running all steps and I get following error**
```bash
$ make
tools/local_server.sh
Starting compass watch
Starting webpack
Starting rethinkdb
Starting flask server
Traceback (most recent call last):
  File "web/server.py", line 4, in <module>
    from web.cache import cache
  File "/home/deltax/vim-awesome/web/cache.py", line 3, in <module>
    from flask.ext.cache import Cache
  File "/usr/lib/python3.6/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/flask_cache/__init__.py", line 18, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
make: *** [Makefile:6: local] Speicherzugriffsfehler (Speicherauszug erstellt)
[1]    27454 terminated  make
```
I also installed the ruby compass modul and all required python packages using the pip command. Currently I use arch so I modify the Makefile from python .... to python2, to make sure all scripts get executed with python2.7. 

**Here are my specs:**
**OS:** ARCH
**Kernel:** 4.10.13-1-ARCH
**Python version:**  Python 2.7.13 and Python 3.6
**Ruby:** 2.4

I make sure I install all modules for both versions
```bash
sudo pip2 install -r requirements.txt
sudo pip install -r requirements.txt
```

I installed also ruby-compass
```bash
yaourt --noconfirm ruby-compass
```

**Comment by deltaxflux** [comment]
Fixed it

**Comment by captbaritone** [comment]
Do you mind sharing what the issue was, in case someone else hits the same issue?

**Comment by deltaxflux** [comment]
I make a quick pull request
