### ISSUE TITLE
Plugin scraping is failing `repo_name` assertion

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#96]
Here's the error we are getting:
```
Scraping plugins from github.com...
    scraping ~/.fzf ...ERROR:root:scrape.py: error in <function scrape_github_plugins at 0x7f1cd1d96578>
Traceback (most recent call last):
  File "/home/vim/vim-awesome/tools/scrape/scrape.py", line 54, in <module>
    scrape_fn(args.number)
  File "/home/vim/vim-awesome/tools/scrape/scrape.py", line 9, in scrape_github_plugins
    github.scrape_plugin_repos(num)
  File "/home/vim/vim-awesome/tools/scrape/github.py", line 266, in scrape_plugin_repos
    'redirects_from': ('%s/%s' % (repo_owner, repo_name)),
  File "/home/vim/vim-awesome/db/github_repos.py", line 104, in upsert_with_owner_repo
    assert repo['repo_name']
AssertionError
```

It looks like the problem starts with the fact that we've created a `plugin_github_repos` entry for a `github.com/~/.fzf' which is obviously not a valid GitHub repo.

Here is the entry from the database `r.db('vim_awesome').table('plugin_github_repos').filter({owner: '~'});`:

```
{
"from_submission": null ,
"from_vim_scripts": [ ],
"id":  "06ba1cc7-7593-4023-8f8f-01bc88aabb31" ,
"is_blacklisted": false ,
"is_fork": false ,
"last_scraped_at": 0 ,
"owner":  "~" ,
"plugin_manager_users": 1 ,
"redirects_from":  "" ,
"redirects_to":  "" ,
"repo_data": { } ,
"repo_id":  "" ,
"repo_name":  ".fzf" ,
"times_scraped": 0
}
```

**Comment by captbaritone** [comment]
Strange!

For whatever reason `https://github.com/~/.fzf` does not return 404, but instead redirects you to `https://github.com`. Our code currently assumes that if we look for a repo and it redirects, the resulting URL is a valid repo.

https://github.com/divad12/vim-awesome/blob/master/tools/scrape/github.py#L253-L267
